apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: letsencrypt
  name: letsencrypt
  namespace: openshift-ingress-operator
rules:
- apiGroups:
  - "operator.openshift.io"
  resources:
  - ingresscontrollers
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete