apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: letsencrypt
  name: letsencrypt
  namespace: openshift-ingress
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete