apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-aws-creds
  labels:
    app: letsencrypt
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    helm.sh/appVersion: "{{ .Chart.AppVersion }}"
    helm.sh/revision: "{{ .Release.Revision }}"
data:
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY | b64enc }}