apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-certs
  labels:
    app: letsencrypt
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    helm.sh/appVersion: "{{ .Chart.AppVersion }}"
    helm.sh/revision: "{{ .Release.Revision }}"
data:
{{ (.Files.Glob "files/certificates/*.com/*").AsSecrets | indent 2 }}