apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: letsencrypt
  name: letsencrypt
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: gepardec/openshift-letsencrypt
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source